---
title: "alignment_correlations"
author: "Joseph Denby"
date: "12/20/2018"
output: html_document
---

```{r}
library(knitr)
library(data.table)
library(tidyverse)
library(readr)
library(stringr)
library(DT)
library(tidytext)
library(RSQLite)
library(DBI)
library(here)
library(feather)
library(magrittr)
library(zoo)
library(RMySQL)
library(rstan)

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

```{r Load Fit Stats}
fit_stats <- read_feather("results/together_fit_stats.feather")
old_model_stats <- read_feather("stanfits/oldmodel_cis.feather")
```

```{r ldp_functions}
source("read_ldp.R")
```

```{r, eval=T, message=FALSE}
MIN_VISITS <- 5

Mode <- function(x) {
  x <- x[!is.na(x)]
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

#### Load and Clean Data
# Read in LDP data
ldp <- connect_to_ldp()

# subject demographics
demos <- get_table(ldp, "subjects") %>%
        filter(lesion == "") %>%
        select(id, sex, race, ethn) %>%
        collect()

# visits information and more subject demographics
visits <- get_table(ldp, "home_visits") %>%
  distinct(id, age_years, subject, visit_type, completed, income_category, 
           mother_education) %>%
  collect() %>%
  filter(visit_type != "SB5") %>%
  mutate(visit_type = as.numeric(gsub("[^0-9]", "", visit_type))) %>%
  rename(visit = visit_type) %>%
  mutate(completed = as.logical(completed),
         income_category = as.numeric(income_category))

subjs <- visits %>%
  group_by(subject) %>%
  summarise(completed = sum(completed),
            income_category = Mode(income_category),
            mother_education = Mode(mother_education)) %>%
  filter(completed >= 5) %>%
  select(-completed) %>%
  right_join(demos, by = c("subject" = "id"))

session_ages <- visits %>%
        filter(subject %in% subjs$subject, completed) %>%
        select(subject, visit, age_years) %>%
        rename(age = age_years) %>%
        arrange(subject, visit)
```

Get other measures
```{r load_measures}
# subject level ppvt info
ppvt <- get_table(ldp, "ppvt") %>%
  collect() %>%
  select(-id) %>%
  rename(id = visit) %>%
  left_join(visits) %>%
  filter(subject %in% subjs$subject) %>%
  rename(ppvt = ppvt_raw) %>%
  select(subject, visit, age_years, ppvt)
  
cdi_ws <- get_table(ldp, "cdi_words_and_sentences") %>%
  select(id, visit, cdis_1a1_num, cdis_2e_num) %>%
  collect() %>%
  select(-id) %>%
  rename(id = visit) %>%
  left_join(visits) %>%
  filter(subject %in% subjs$subject) %>%
  rename(cdi_ws = cdis_1a1_num, sent_comp = cdis_2e_num) %>%
  select(subject, visit, age_years, cdi_ws, sent_comp) %>%
  arrange(subject, visit)

syntax <- get_table(ldp, "syntax") %>%
  collect() %>%
  select(-id) %>%
  rename(id = visit) %>%
  left_join(visits) %>%
  filter(subject %in% subjs$subject) %>%
  rename(syntax = syntax_raw) %>%
  select(subject, visit, age_years, syntax) %>% 
  arrange(subject, visit)

wppsi <- get_table(ldp, "wppsi_block_design") %>%
  collect() %>%
  select(-id) %>%
  rename(id = visit) %>%
  left_join(visits) %>%
  filter(subject %in% subjs$subject) %>%
  arrange(subject, visit) %>%
  filter(!is.na(wppsi_block_raw)) %>%
  select(subject, visit, age_years, wppsi_block_raw) %>%
  rename(wppsi_block = wppsi_block_raw)

measures <- full_join(ppvt, cdi_ws, by = c("subject", "visit", "age_years")) %>%
  full_join(syntax, by = c("subject", "visit", "age_years")) %>%
  full_join(wppsi, by = c("subject", "visit", "age_years")) %>%
  gather(measure, value, ppvt, cdi_ws, sent_comp, syntax, wppsi_block) %>%
  filter(!is.na(value)) %>%
  arrange(subject, measure, visit) %>%
  mutate(person = "child")

```

```{r correlate (avg subject) ppvt }
avg_subj_ppvt <- measures %>% 
  filter(measure == 'ppvt') %>%
  ungroup() %>% 
  group_by(subject) %>% 
  summarise(value= mean(value)) %>% 
  rename(ppvt = value)

ppvt_fit_stats <- left_join(avg_subj_ppvt, fit_stats, by = c('subject'='subj')) %>% 
  na.omit()

# correlations
ppvt_fit_stats %>% 
  group_by(measure) %>% 
  mutate(correlation = cor(ppvt,value)) %>% 
  select(measure, correlation) %>% 
  distinct()
```

```{r}
fit_stats %>% 
  group_by(measure) %>% 
  summarise(value = mean(value))
```

```{r}
avg_subj_measure <- measures %>% 
  group_by(subject, measure) %>% 
  summarise(value= mean(value)) 

old_stats <- old_model_stats %>%
  filter(type == "speaker") %>%
  mutate(id = as.numeric(id)) %>%
  left_join(avg_subj_measure, fit_stats, by = c("id" = "subject")) %>%
  filter(!is.na(value))
  
old_stats %>% 
  group_by(person, parameter, measure) %>% 
  mutate(correlation = cor(value, mean)) %>% 
  select(person, measure, parameter, correlation) %>% 
  distinct() %>%
  arrange(person, measure, parameter) %>%
  View()

```


```{r Old Fit with Demos and PPVT}

raw_long_present <- read_feather('data/RECOUNT_long_present.feather')

long_present <- raw_long_present %>% 
  arrange(subject, session, category, run) %>%
  group_by(subject, session, category) %>%
  mutate(lag_count = lag(count)) %>%
  filter(!is.na(lag_count)) %>%
  group_by(subject, session, person, category) %>%
  mutate(BA = count > 0 & lag_count > 0,
         notBA = count == 0 & lag_count > 0,
         BnotA = count > 0 & lag_count == 0,
         notBnotA = count == 0 & lag_count == 0) %>%
  summarise_at(vars(BA,notBA,BnotA,notBnotA), sum) %>%
  mutate(NumUtterancesAB = BA +notBA, 
         NumUtterancesNotAB = BnotA + notBnotA) %>%
  rename(CountsAB = BA, CountsNotAB = BnotA) %>%
    select(-notBA, - notBnotA)

# Join demographic info and ppvt onto utterance data; convert categorical info to binary
long_present_demos <- long_present %>% 
  left_join(subjs, by = 'subject') %>% 
  left_join(ppvt, by= 'subject') %>% 
  na.omit() %>% 
  mutate(female = as.numeric(sex == 'F'),
         male = as.numeric(sex == 'M'),
         white = as.numeric(sex == 'WH'),
         black = as.numeric(sex == 'BL'),
         multi = as.numeric(sex == '2+'),
         income_category = income_category - 1)

# treat mother_ed as ordinal variable
conversion = c("Some High School"=0, "High School or GED"=1, "Some College or Trade School"=2, "Bachelor's Degree"=3, "Advanced Degree"=4)
long_present_demos$mother_education = conversion[long_present_demos$mother_education]

liwc <- read_tsv("word_lists/liwc2007_converted.tsv", col_names = FALSE) %>%
  rename(word = X1, category = X2)

long_present <- long_present_demos %>%
  ungroup() %>%
  mutate(uid = paste0(subject, "_", person)) %>%
  mutate(uid = as.numeric(as.factor(uid))) %>% 
  mutate(parentid = case_when(person == 'Parent' ~ uid,
                              TRUE ~ uid + 1),
         childid = case_when(person == 'Child' ~ uid,
                             TRUE ~ uid - 1))

ppvt_slope_by_subject <- long_present %>% 
  group_by(subject) %>% 
  select(subject, ppvt, age_years) %>% 
  distinct() %>% 
  do(model = lm(ppvt~age_years, .)$coefficients[2][[1]]) %>% 
  mutate(model = replace_na(model,0))

long_present <- long_present %>% 
  left_join(ppvt_slope_by_subject, by = 'subject') 

write_feather(long_present, 'ppvt_with_demos.feather')

## STAN DATA ##
MidAge <- median(long_present$session)
NumMarkers <- length(unique(liwc$category))
NumSubPops <- length(unique(long_present$person))
NumSpeakers <- length(unique(long_present$uid))
NumObservations <- dim(long_present)[1]
NumSex <- length(unique(long_present$sex))
NumMomEd <- length(unique(long_present$mother_education))
SpeakerSubPop <- long_present %>% 
  distinct(person, uid) %>%
  mutate(subpop =  as.numeric(as.factor(person))) %>%
  pull(subpop) # Child - 1; Parent - 2
SpeakerMomEd <- long_present %>% 
  mutate(mother_education = mother_education + 1) %>% 
  distinct(uid, mother_education) %>%
  pull(mother_education)
SpeakerSex <- long_present %>% 
  distinct(uid, sex) %>%
  mutate(sex =  as.numeric(as.factor(sex))) %>%
  pull(sex) # Female - 1; Male - 2
SpeakerId <-long_present$uid
SpeakerAge <- long_present$session
MarkerType <- as.numeric(as.factor(long_present$category)) #see liwc_markers
NumUtterancesAB <- long_present$NumUtterancesAB
NumUtterancesNotAB <- long_present$NumUtterancesNotAB
CountsAB <- long_present$CountsAB
CountsNotAB <- long_present$CountsNotAB
StdDev <- 1

ppvt_vals <- long_present$ppvt
age_years <- long_present$age_years
income_category <- long_present$income_category
mother_education <- long_present$mother_education
female <- long_present$female
black <- long_present$black
multi <- long_present$multi
ppvt_slopes <- long_present$model
parentid <- long_present$parentid
childid <- long_present$childid
###############

fit <- stan("stan_models/alignmenthierarchicaldemos.stan",
            chains = 1,
            iter = 50)


fit_hierarchical <- stan("stan_models/oldalignment_w_demos.stan", 
                         chains = 1, iter = 200)

saveRDS(fit_hierarchical, 'stanfits/oldmodeldemos_short.rds')
```

```{r fit extraction}
raw_long_present <- read_feather('data/RECOUNT_long_present.feather')

long_present <- raw_long_present %>% 
  arrange(subject, session, category, run) %>%
  group_by(subject, session, category) %>%
  mutate(lag_count = lag(count)) %>%
  filter(!is.na(lag_count)) %>%
  group_by(subject, session, person, category) %>%
  mutate(BA = count > 0 & lag_count > 0,
         notBA = count == 0 & lag_count > 0,
         BnotA = count > 0 & lag_count == 0,
         notBnotA = count == 0 & lag_count == 0) %>%
  summarise_at(vars(BA,notBA,BnotA,notBnotA), sum) %>%
  mutate(NumUtterancesAB = BA +notBA, 
         NumUtterancesNotAB = BnotA + notBnotA) %>%
  rename(CountsAB = BA, CountsNotAB = BnotA) %>%
    select(-notBA, - notBnotA)

long_present <- long_present %>%
  ungroup() %>%
  mutate(uid = paste0(subject, "_", person)) %>%
  mutate(uid = as.numeric(as.factor(uid)))



fit_hierarchical <- readRDS('stanfits/oldmodeldemos_short.rds')
fit_hierarchical <- readRDS('newhierdemos200iters.rds')

SE_UPPER <- .84
SE_LOWER <- .16


demopars <- names(fit_hierarchical) %>%
  as_data_frame() %>%
  filter(str_detect(value, "mu") | str_detect(value, 'ppvt') | str_detect(value, 'sigma'),
         !str_detect(value, "observation"),
         !str_detect(value, "mu_ab"),
         !str_detect(value, "mu_notab")) %>%
  pull()

demoparameters <- extract(fit_hierarchical, demopars) %>%
  bind_rows(.id = "sample") %>%
  gather(measure, value, -sample) %>%
  group_by(measure) %>%
  summarise(mean = mean(value), se_upper = quantile(value,SE_UPPER), 
            se_lower = quantile(value,SE_LOWER))
  

pars <- names(fit_hierarchical) %>%
  as_data_frame() %>%
  filter(!str_detect(value, "Marker"), 
         !str_detect(value, "observation"),
         !str_detect(value, "mu_ab"),
         !str_detect(value, "mu_notab"),
          !str_detect(value, "lp__")) %>%
  pull()

demo_abs <- names(fit_hierarchical) %>% 
  as_data_frame() %>% 
  filter(str_detect(value, "mom_ed") | str_detect(value, "gender_ab")) %>% 
  pull()

demo_ab_parameters <- extract(fit_hierarchical, demo_abs) %>%
  bind_rows(.id = "sample") %>%
  gather(measure, value, -sample) %>%
  group_by(measure) %>%
  summarise(mean = mean(value), se_upper = quantile(value,SE_UPPER), 
            se_lower = quantile(value,SE_LOWER))

parameter_cis <- extract(fit_hierarchical, pars) %>%
  bind_rows(.id = "sample") %>%
  gather(measure, value, -sample) %>%
  group_by(measure) %>%
  summarise(mean = mean(value), se_upper = quantile(value,SE_UPPER), 
            se_lower = quantile(value,SE_LOWER)) %>%
  ungroup() %>% 
  mutate(measure = gsub("eta_ab","eta-ab", measure)) %>%
  separate(measure, into = c("parameter", "type") , sep = "_", 
           extra = "merge") %>%
  mutate(id = gsub("[^0-9]*","", str_extract(type, "\\[[^()]+\\]")),
         type = gsub("\\[[^()]+\\]", "", type),
         type = factor(type, levels = c("pop", "subpop", "speaker")),
         id = case_when(
           is.na(id) ~ "pop",
           type == "subpop" & id == 1 ~ "child",
           type == "subpop" & id == 2 ~ "parent",
           T ~ id)
         ) %>%
  left_join(distinct(long_present, subject, uid, person) %>% 
              mutate(uid = as.character(uid)), by = c("id" = "uid")) %>%
  arrange(type, parameter) %>%
  mutate(id = if_else(is.na(subject), id, as.character(subject))) %>%
  select(-subject)

parameter_cis %>% 
  filter(parameter == 'mom_ed')

avg_subj_measure <- measures %>% 
  group_by(subject, measure) %>% 
  summarise(value= mean(value)) 

old_stats <- old_model_stats %>%
  filter(type == "speaker") %>%
  mutate(id = as.numeric(id)) %>%
  left_join(avg_subj_measure, fit_stats, by = c("id" = "subject")) %>%
  filter(!is.na(value))

new_old_stats <- parameter_cis %>%
  filter(type == "speaker") %>%
  mutate(id = as.numeric(id)) %>%
  left_join(avg_subj_measure, fit_stats, by = c("id" = "subject")) %>%
  filter(!is.na(value))
  
old_cors <- old_stats %>% 
  group_by(person, parameter, measure) %>% 
  mutate(correlation = cor(value, mean)) %>% 
  select(person, measure, parameter, correlation) %>% 
  distinct() %>%
  arrange(person, measure, parameter) 

new_old_cors <- new_old_stats %>% 
  group_by(person, parameter, measure) %>% 
  mutate(correlation = cor(value, mean)) %>% 
  select(person, measure, parameter, correlation) %>% 
  distinct() %>%
  arrange(person, measure, parameter) 

together_cors <- old_cors %>% 
  left_join(new_old_cors, by = c('person', 'measure', 'parameter'), suffix = c(".nodemos",".demos"))

write_csv(together_cors, 'together_cors.csv')
```

