---
title: "child_fit_utterance_model"
author: "Jo Denby"
date: "2/7/2018"
output: html_document
---
```{r}
library(tidyverse)
library(stringr)
library(rstan)
library(bayesplot)
library(tidyboot)
library(shinystan)
library(lme4)

library(feather)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```


```{r}
utterances <- read_feather("utterances.feather")

one_file_utts <- utterances %>%
  filter(!is.na(c_chat)) %>%
  select(session,c_chat,subject) %>%
  mutate(length = str_count(c_chat, " ")) %>%
  filter(length > 0)

childIDs <-  cbind(unique(one_file_utts$subject), seq(1,length(unique(one_file_utts$subject)))) %>%
  as.data.frame()
colnames(childIDs) <- c('subject', 'subject_numeral')


one_file_utts <- one_file_utts %>%
  left_join(childIDs) %>%
  #mutate(mean_length = mean(length)) %>%
  mutate(session = session - 6) %>%
  group_by(subject_numeral, session) %>%
  #filter(subject_numeral %in% c(1,2)) %>%
  #filter(session %in% c(-1,0,1)) %>%
  ungroup() 

######## STAN DATA ########################
utt_child <- one_file_utts$subject_numeral
numChildren <- length(unique(utt_child))
numLengths <- length(one_file_utts$length)
utt_length <- one_file_utts$length
utt_session <- one_file_utts$session
###########################################

fit <- stan(file = "child_utt_length.stan", chains = 1)

```

